packages:
  - api
  - docs
  - demo/*
  - demo/custom/valaxy-theme-custom
  - packages/*
  - packages/@valaxyjs/*
  - scripts

catalogs:
  build:
    '@iconify-json/ant-design': ^1.2.5
    '@iconify-json/carbon': ^1.2.13
    '@iconify-json/logos': ^1.2.9
    '@iconify-json/ri': ^1.2.5
    '@iconify-json/simple-icons': ^1.2.52
    '@iconify-json/vscode-icons': ^1.2.30
    '@intlify/unplugin-vue-i18n': ^11.0.1
    '@unhead/addons': ^2.0.17
    '@unhead/schema-org': ^2.0.17
    '@unhead/vue': ^2.0.17
    consola: ^3.4.2
    typescript: ^5.9.2
    unbuild: ^3.6.1
    unhead: ^2.0.17
    unplugin-vue-router: ^0.15.0
    vite: ^7.1.7
    vue-i18n: ^11.1.12
    zx: ^8.8.3
  frontend:
    '@primevue/themes': ^4.3.9
    primevue: ^4.3.9
    vitepress: ^2.0.0-alpha.12
    vue: ^3.5.21
onlyBuiltDependencies:
  - vue-demi
  - esbuild
