packages:
  - api
  - docs
  - demo/*
  - demo/custom/valaxy-theme-custom
  - packages/*
  - packages/@valaxyjs/*
  - scripts

catalogs:
  build:
    '@iconify-json/ant-design': ^1.2.5
    '@iconify-json/carbon': ^1.2.10
    '@iconify-json/logos': ^1.2.4
    '@iconify-json/ri': ^1.2.5
    '@iconify-json/simple-icons': ^1.2.43
    '@iconify-json/vscode-icons': ^1.2.23
    '@unhead/addons': ^2.0.12
    '@unhead/schema-org': ^2.0.12
    '@unhead/vue': ^2.0.12
    consola: ^3.4.2
    typescript: ^5.8.3
    unbuild: ^3.5.0
    unhead: ^2.0.12
    unplugin-vue-router: ^0.14.0
    vite: ^7.0.5
    vue-i18n: ^11.1.10
    zx: ^8.7.1
  frontend:
    '@primevue/themes': ^4.3.6
    primevue: ^4.3.6
    vue: ^3.5.17

onlyBuiltDependencies:
  - vue-demi
  - esbuild
