packages:
  - api
  - docs
  - demo/*
  - demo/custom/valaxy-theme-custom
  - packages/*
  - packages/@valaxyjs/*
  - scripts

catalogs:
  build:
    '@iconify-json/ant-design': ^1.2.5
    '@iconify-json/carbon': ^1.2.11
    '@iconify-json/logos': ^1.2.5
    '@iconify-json/ri': ^1.2.5
    '@iconify-json/simple-icons': ^1.2.45
    '@iconify-json/vscode-icons': ^1.2.23
    '@unhead/addons': ^2.0.13
    '@unhead/schema-org': ^2.0.13
    '@unhead/vue': ^2.0.13
    consola: ^3.4.2
    typescript: ^5.9.2
    unbuild: ^3.6.0
    unhead: ^2.0.13
    unplugin-vue-router: ^0.14.0
    vite: ^7.0.6
    vue-i18n: ^11.1.11
    zx: ^8.7.2
  frontend:
    '@primevue/themes': ^4.3.7
    primevue: ^4.3.7
    vitepress: ^2.0.0-alpha.9
    vue: ^3.5.18
onlyBuiltDependencies:
  - vue-demi
  - esbuild
