packages:
  - api
  - docs
  - demo/*
  - demo/custom/valaxy-theme-custom
  - packages/*
  - packages/@valaxyjs/*
  - scripts

catalogs:
  build:
    '@iconify-json/ant-design': ^1.2.5
    '@iconify-json/carbon': ^1.2.13
    '@iconify-json/logos': ^1.2.9
    '@iconify-json/ri': ^1.2.5
    '@iconify-json/simple-icons': ^1.2.49
    '@iconify-json/vscode-icons': ^1.2.30
    '@unhead/addons': ^2.0.14
    '@unhead/schema-org': ^2.0.14
    '@unhead/vue': ^2.0.14
    consola: ^3.4.2
    typescript: ^5.9.2
    unbuild: ^3.6.1
    unhead: ^2.0.14
    unplugin-vue-router: ^0.15.0
    vite: ^7.1.3
    vue-i18n: ^11.1.11
    zx: ^8.8.1
  frontend:
    '@primevue/themes': ^4.3.7
    primevue: ^4.3.7
    vitepress: ^2.0.0-alpha.12
    vue: ^3.5.20
onlyBuiltDependencies:
  - vue-demi
  - esbuild
